/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.crud.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the crud service. Represents a row in the &quot;ActualizacionDeDatos_crud&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.crud.model.impl.crudModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.crud.model.impl.crudImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see crud
 * @generated
 */
@ProviderType
public interface crudModel extends BaseModel<crud>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a crud model instance should use the {@link crud} interface instead.
	 */

	/**
	 * Returns the primary key of this crud.
	 *
	 * @return the primary key of this crud
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this crud.
	 *
	 * @param primaryKey the primary key of this crud
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the crud ID of this crud.
	 *
	 * @return the crud ID of this crud
	 */
	public long getCrudId();

	/**
	 * Sets the crud ID of this crud.
	 *
	 * @param crudId the crud ID of this crud
	 */
	public void setCrudId(long crudId);

	/**
	 * Returns the group ID of this crud.
	 *
	 * @return the group ID of this crud
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this crud.
	 *
	 * @param groupId the group ID of this crud
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this crud.
	 *
	 * @return the company ID of this crud
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this crud.
	 *
	 * @param companyId the company ID of this crud
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this crud.
	 *
	 * @return the user ID of this crud
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this crud.
	 *
	 * @param userId the user ID of this crud
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this crud.
	 *
	 * @return the user uuid of this crud
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this crud.
	 *
	 * @param userUuid the user uuid of this crud
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this crud.
	 *
	 * @return the user name of this crud
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this crud.
	 *
	 * @param userName the user name of this crud
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this crud.
	 *
	 * @return the create date of this crud
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this crud.
	 *
	 * @param createDate the create date of this crud
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this crud.
	 *
	 * @return the modified date of this crud
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this crud.
	 *
	 * @param modifiedDate the modified date of this crud
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nombre of this crud.
	 *
	 * @return the nombre of this crud
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this crud.
	 *
	 * @param nombre the nombre of this crud
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the apellido of this crud.
	 *
	 * @return the apellido of this crud
	 */
	@AutoEscape
	public String getApellido();

	/**
	 * Sets the apellido of this crud.
	 *
	 * @param apellido the apellido of this crud
	 */
	public void setApellido(String apellido);

	/**
	 * Returns the edad of this crud.
	 *
	 * @return the edad of this crud
	 */
	@AutoEscape
	public String getEdad();

	/**
	 * Sets the edad of this crud.
	 *
	 * @param edad the edad of this crud
	 */
	public void setEdad(String edad);

	/**
	 * Returns the documento of this crud.
	 *
	 * @return the documento of this crud
	 */
	@AutoEscape
	public String getDocumento();

	/**
	 * Sets the documento of this crud.
	 *
	 * @param documento the documento of this crud
	 */
	public void setDocumento(String documento);

	/**
	 * Returns the tipo documento of this crud.
	 *
	 * @return the tipo documento of this crud
	 */
	@AutoEscape
	public String getTipoDocumento();

	/**
	 * Sets the tipo documento of this crud.
	 *
	 * @param tipoDocumento the tipo documento of this crud
	 */
	public void setTipoDocumento(String tipoDocumento);

	/**
	 * Returns the nacimiento of this crud.
	 *
	 * @return the nacimiento of this crud
	 */
	public Date getNacimiento();

	/**
	 * Sets the nacimiento of this crud.
	 *
	 * @param nacimiento the nacimiento of this crud
	 */
	public void setNacimiento(Date nacimiento);

	/**
	 * Returns the direccion of this crud.
	 *
	 * @return the direccion of this crud
	 */
	@AutoEscape
	public String getDireccion();

	/**
	 * Sets the direccion of this crud.
	 *
	 * @param direccion the direccion of this crud
	 */
	public void setDireccion(String direccion);

	/**
	 * Returns the ciudad of this crud.
	 *
	 * @return the ciudad of this crud
	 */
	@AutoEscape
	public String getCiudad();

	/**
	 * Sets the ciudad of this crud.
	 *
	 * @param ciudad the ciudad of this crud
	 */
	public void setCiudad(String ciudad);

	/**
	 * Returns the telefono fijo of this crud.
	 *
	 * @return the telefono fijo of this crud
	 */
	@AutoEscape
	public String getTelefonoFijo();

	/**
	 * Sets the telefono fijo of this crud.
	 *
	 * @param telefonoFijo the telefono fijo of this crud
	 */
	public void setTelefonoFijo(String telefonoFijo);

	/**
	 * Returns the telefono celular of this crud.
	 *
	 * @return the telefono celular of this crud
	 */
	@AutoEscape
	public String getTelefonoCelular();

	/**
	 * Sets the telefono celular of this crud.
	 *
	 * @param telefonoCelular the telefono celular of this crud
	 */
	public void setTelefonoCelular(String telefonoCelular);

}